export default [
  { name: "bug", url: "/images/cards/bg_normal.jpg" },
  { name: "dark", url: "/images/cards/bg_normal.jpg" },
  { name: "dragon", url: "/images/cards/bg_normal.jpg" },
  { name: "electric", url: "/images/cards/bg_electric.jpg" },
  { name: "fairy", url: "/images/cards/bg_normal.jpg" },
  { name: "fighting", url: "/images/cards/bg_normal.jpg" },
  { name: "fire", url: "/images/cards/bg_fire.jpg" },
  { name: "flying", url: "/images/cards/bg_flying.jpg" },
  { name: "ghost", url: "/images/cards/bg_ghost.jpg" },
  { name: "grass", url: "/images/cards/bg_grass.jpg" },
  { name: "ground", url: "/images/cards/bg_normal.jpg" },
  { name: "ice", url: "/images/cards/bg_ice.jpg" },
  { name: "normal", url: "/images/cards/bg_normal.jpg" },
  { name: "poison", url: "/images/cards/bg_poison.jpg" },
  { name: "psychic", url: "/images/cards/bg_psychic.jpg" },
  { name: "rock", url: "/images/cards/bg_rock.jpg" },
  { name: "shadow", url: "/images/cards/bg_normal.jpg" },
  { name: "steel", url: "/images/cards/bg_normal.jpg" },
  { name: "unknown", url: "/images/cards/bg_normal.jpg" },
  { name: "water", url: "/images/cards/bg_water.jpg" },
];
